import {parseFixtureConfig} from "../parser.js";

export default parseFixtureConfig({
    type: "bar",
    model: "Beamz LCB 224",
    modes: [
        {
            name: "3ch",
            props: ["red", "green", "blue"],
        },
        {
            name: "5ch",
            props: [{type: "dimmer", activeDefault: 255}, "strobe", "red", "green", "blue"],
        },
        {
            name: "48ch",
            props: [
                {type: "red", repeats: 8, every: 3},
                {type: "green", repeats: 8, every: 3},
                {type: "blue", repeats: 8, every: 3},
                {type: "red", repeats: 8, every: 3},
                {type: "green", repeats: 8, every: 3},
                {type: "blue", repeats: 8, every: 3},
            ],
        },
        {
            name: "53ch",
            props: [
                {type: "dimmer", activeDefault: 255},
                {type: "red", repeats: 8, every: 3},
                {type: "green", repeats: 8, every: 3},
                {type: "blue", repeats: 8, every: 3},
                {type: "red", repeats: 8, every: 3},
                {type: "green", repeats: 8, every: 3},
                {type: "blue", repeats: 8, every: 3},
                {
                    type: "custom",
                    label: "Mode",
                    modes: [
                        {ch_val: 0, val: "Off", custom: "stop"},
                        {ch_val: 10, val: "Static Colour", custom: "stop"},
                        {ch_val: 14, val: "Show 1", custom: "stop"},
                        {ch_val: 18, val: "Show 2", custom: "stop"},
                        {ch_val: 22, val: "Show 3", custom: "stop"},
                        {ch_val: 26, val: "Show 4", custom: "stop"},
                        {ch_val: 30, val: "Show 5", custom: "stop"},
                        {ch_val: 34, val: "Show 6", custom: "stop"},
                        {ch_val: 38, val: "Show 7", custom: "stop"},
                        {ch_val: 42, val: "Show 8", custom: "stop"},
                        {ch_val: 46, val: "Show 9", custom: "stop"},
                        {ch_val: 50, val: "Show 10", custom: "stop"},
                        {ch_val: 54, val: "Show 11", custom: "stop"},
                        {ch_val: 58, val: "Show 12", custom: "stop"},
                        {ch_val: 62, val: "Show 13", custom: "stop"},
                        {ch_val: 66, val: "Show 14", custom: "stop"},
                        {ch_val: 70, val: "Show 15", custom: "stop"},
                        {ch_val: 74, val: "Show 16", custom: "stop"},
                        {ch_val: 78, val: "Show 17", custom: "stop"},
                        {ch_val: 82, val: "Show 18", custom: "stop"},
                        {ch_val: 86, val: "Show 19", custom: "stop"},
                        {ch_val: 90, val: "Show 20", custom: "stop"},
                        {ch_val: 94, val: "Show 21", custom: "stop"},
                        {ch_val: 98, val: "Show 22", custom: "stop"},
                        {ch_val: 102, val: "Show 23", custom: "stop"},
                        {ch_val: 106, val: "Show 24", custom: "stop"},
                        {ch_val: 110, val: "Show 25", custom: "stop"},
                        {ch_val: 114, val: "Show 26", custom: "stop"},
                        {ch_val: 118, val: "Show 27", custom: "stop"},
                        {ch_val: 122, val: "Show 28", custom: "stop"},
                        {ch_val: 126, val: "Show 29", custom: "stop"},
                        {ch_val: 130, val: "Show 30", custom: "stop"},
                        {ch_val: 134, val: "Show 31", custom: "stop"},
                        {ch_val: 138, val: "Show 32", custom: "stop"},
                        {ch_val: 142, val: "Show 33", custom: "stop"},
                        {ch_val: 146, val: "Show 34", custom: "stop"},
                        {ch_val: 150, val: "Show 35", custom: "stop"},
                        {ch_val: 154, val: "Show 36", custom: "stop"},
                        {ch_val: 158, val: "Show 37", custom: "stop"},
                        {ch_val: 162, val: "Show 38", custom: "stop"},
                        {ch_val: 166, val: "Show 39", custom: "stop"},
                        {ch_val: 170, val: "Show 40", custom: "stop"},
                        {ch_val: 174, val: "Show 41", custom: "stop"},
                        {ch_val: 178, val: "Show 42", custom: "stop"},
                        {ch_val: 182, val: "Show 43", custom: "stop"},
                        {ch_val: 186, val: "Show 44", custom: "stop"},
                        {ch_val: 190, val: "Show 45", custom: "stop"},
                        {ch_val: 194, val: "Show 46", custom: "stop"},
                        {ch_val: 198, val: "Show 47", custom: "stop"},
                        {ch_val: 202, val: "Show 48", custom: "stop"},
                        {ch_val: 206, val: "Show 49", custom: "stop"},
                        {ch_val: 210, val: "Show 50", custom: "stop"},
                        {ch_val: 214, val: "Show 51", custom: "stop"},
                        {ch_val: 218, val: "Show 52", custom: "stop"},
                        {ch_val: 222, val: "Show 53", custom: "stop"},
                        {ch_val: 226, val: "Show 54", custom: "stop"},
                        {ch_val: 230, val: "Auto Mode", custom: "stop"},
                        {ch_val: 234, val: "DMX Sound mode 1", custom: "stop"},
                        {ch_val: 238, val: "DMX Sound mode 2", custom: "stop"},
                        {ch_val: 242, val: "DMX Sound mode 3", custom: "stop"},
                    ],
                },
                {
                    type: "custom",
                    label: "Pattern",
                    modes: [
                        {ch_val: 0, val: "Off", custom: "stop"},
                        {ch_val: 10, val: "Pattern 1", custom: "stop"},
                        {ch_val: 20, val: "Pattern 2", custom: "stop"},
                        {ch_val: 30, val: "Pattern 3", custom: "stop"},
                        {ch_val: 40, val: "Pattern 4", custom: "stop"},
                        {ch_val: 50, val: "Pattern 5", custom: "stop"},
                        {ch_val: 60, val: "Pattern 6", custom: "stop"},
                        {ch_val: 70, val: "Pattern 7", custom: "stop"},
                        {ch_val: 80, val: "Patterm 8", custom: "stop"},
                        {ch_val: 90, val: "Pattern 9", custom: "stop"},
                        {ch_val: 100, val: "Pattern 10", custom: "stop"},
                        {ch_val: 110, val: "Pattern 11", custom: "stop"},
                        {ch_val: 120, val: "Pattern 12", custom: "stop"},
                        {ch_val: 130, val: "Pattern 13", custom: "stop"},
                        {ch_val: 140, val: "Pattern 14", custom: "stop"},
                        {ch_val: 150, val: "Pattern 15", custom: "stop"},
                        {ch_val: 160, val: "Pattern 16", custom: "stop"},
                        {ch_val: 170, val: "Pattern 17", custom: "stop"},
                        {ch_val: 180, val: "Pattern 18", custom: "stop"},
                        {ch_val: 190, val: "Pattern 19", custom: "stop"},
                        {ch_val: 200, val: "Pattern 20", custom: "stop"},
                        {ch_val: 210, val: "Pattern 21", custom: "stop"},
                        {ch_val: 220, val: "Pattern 22", custom: "stop"},
                        {ch_val: 230, val: "Pattern 23", custom: "stop"},
                        {ch_val: 240, val: "Pattern 24", custom: "stop"},
                        {ch_val: 250, val: "Pattern 25", custom: "stop"},
                    ],
                },
                {
                    type: "custom",
                    label: "Color Speed",
                },
                "strobe",
            ],
        },
    ],
});
